---
title: "How to: Handle an Exception Using try-catch (C# Programming Guide)"
ms.custom: na
ms.date: 09/22/2016
ms.prod: visual-studio-dev14
ms.reviewer: na
ms.suite: na
ms.technology: 
  - devlang-csharp
ms.tgt_pltfrm: na
ms.topic: article
H1: How to: Handle an Exception Using try/catch (C# Programming Guide)
dev_langs: 
  - CSharp
helpviewer_keywords: 
  - exception handling [C#], try/catch blocks
  - exceptions [C#], try/catch blocks
  - try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
caps.latest.revision: 18
translation.priority.ht: 
  - de-de
  - ja-jp
---
# How to: Handle an Exception Using try-catch (C# Programming Guide)
The purpose of a [try-catch](../vs140/try-catch--csharp-reference-.md) block is to catch and handle an exception generated by working code. Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.  
  
## Example  
 In this example, <xref:System.IndexOutOfRangeException?qualifyHint=False> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException?qualifyHint=False> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.  
  
 [!code[csProgGuideExceptions#5](../vs140/codesnippet/CSharp/how-to--handle-an-exception-using-try-catch--csharp-programming-guide-_1.cs)]
  
  
## Comments  
 The code that causes an exception is enclosed in the `try` block. A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs. The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead. In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException?qualifyHint=False> of the new exception. Because the <xref:System.Exception.InnerException?qualifyHint=False> property is [readonly](../vs140/readonly--csharp-reference-.md), you must assign it in the constructor of the new exception.  
  
## See Also  
 [C# Programming Guide](../vs140/csharp-programming-guide.md)   
 [Exceptions and Exception Handling (Visual C#)](../vs140/exceptions-and-exception-handling--csharp-programming-guide-.md)   
 [Handling Exceptions (Visual C#)](../vs140/exception-handling--csharp-programming-guide-.md)